// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using checkers.Infrastructure.DataBase;

namespace checkers.Migrations
{
    [DbContext(typeof(CheckersDbContext))]
    partial class CheckersDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.2-rtm-30932")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("checkers.Infrastructure.DataBase.Models.Board", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created");

                    b.Property<DateTime>("LastModified");

                    b.HasKey("Id");

                    b.ToTable("Boards");
                });

            modelBuilder.Entity("checkers.Infrastructure.DataBase.Models.Checker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Color");

                    b.Property<DateTime>("Created");

                    b.Property<DateTime>("LastModified");

                    b.Property<bool>("Queen");

                    b.HasKey("Id");

                    b.ToTable("Checkers");
                });

            modelBuilder.Entity("checkers.Infrastructure.DataBase.Models.Square", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BoardId");

                    b.Property<int?>("CheckerId");

                    b.Property<int>("Color");

                    b.Property<DateTime>("Created");

                    b.Property<DateTime>("LastModified");

                    b.Property<int>("X");

                    b.Property<int>("Y");

                    b.HasKey("Id");

                    b.HasIndex("BoardId");

                    b.HasIndex("CheckerId");

                    b.ToTable("Squares");
                });

            modelBuilder.Entity("checkers.Infrastructure.DataBase.Models.Square", b =>
                {
                    b.HasOne("checkers.Infrastructure.DataBase.Models.Board")
                        .WithMany("Squares")
                        .HasForeignKey("BoardId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("checkers.Infrastructure.DataBase.Models.Checker", "Checker")
                        .WithMany()
                        .HasForeignKey("CheckerId");
                });
#pragma warning restore 612, 618
        }
    }
}
